### ISSUE TITLE
Launchpad does not allow fetching arbitrary commits, which now breaks our tests here

### ISSUE THREAD

**Issue by tianon** [docker-library/meta-scripts#25]
```
+ .test/test.sh
failed fetching git repo for "ubuntu" (tags "22.04, jammy-20240111, jammy, latest" on arch "amd64")
failed fetching "e6e3490ad3f[5](https://github.com/docker-library/meta-scripts/actions/runs/7936297386/job/21671258830?pr=24#step:5:6)24ccaa072edafe525f8ca8ac5490:refs/remotes/temp2901481880/temp": server does not support exact SHA1 refspec
failed fetching "refs/tags/dist-jammy-amd[6](https://github.com/docker-library/meta-scripts/actions/runs/7936297386/job/21671258830?pr=24#step:5:7)4-20240111-e6e3490a:refs/remotes/temp29014[8](https://github.com/docker-library/meta-scripts/actions/runs/7936297386/job/21671258830?pr=24#step:5:9)1880/temp": couldn't find remote ref "refs/tags/dist-jammy-amd64-20240111-e6e3490a"
```

We can fix this in a few different ways.  The easiest/quickest temporary fix would be to mirror those old commits to a GitHub repository somewhere and update our test library file to reference it from GitHub instead (I still have these commits locally, so that would be pretty easy -- choosing/naming a repo is much harder; we used to use https://github.com/docker-library/commit-warehouse for this, before GitHub added support for fetching arbitrary commits and before it grew too large to even use anymore :innocent:).

A better long-term fix would probably be to finally convert `busybox` over to use `oci-import` (now that we have #20) which would also allow us to _test_ #20 properly. :smile:

**Comment by tianon** [comment]
Ok, I took both commits from https://github.com/docker-library/meta-scripts/blob/b446700b3ec0b10ef89204ab585ceb862f131da5/.test/library/ubuntu (`fa42be9027eccb928a1f0f43d95ffd9a45d36737` and `e6e3490ad3f524ccaa072edafe525f8ca8ac5490`) and pushed them both into https://github.com/tianon/temp:

- https://github.com/tianon/temp/commit/fa42be9027eccb928a1f0f43d95ffd9a45d36737
- https://github.com/tianon/temp/commit/e6e3490ad3f524ccaa072edafe525f8ca8ac5490

I'll make a PR fixing our test shortly.

**Comment by whalelines** [comment]
Did the behavior of Launchpad change? Why is this test failing now but was not before?

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/pull/13090#issuecomment-1235324351 and following comments -- they only keep a few of their branches (per our request) so users can still inspect slightly older images, but not significantly older ones and this one just crossed the threshold with their update yesterday.
